; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Fenix
AppVerName=Fenix Cliente v5 20130417
AppPublisher=BasePro
AppPublisherURL=http://www.basepro.com.br
AppSupportURL=http://www.basepro.com.br
AppUpdatesURL=http://www.basepro.com.br
DefaultDirName=c:\Fenix
DefaultGroupName=Fenix
OutputDir=H:\fontes\fenixCliente\Cliente
OutputBaseFilename=InstaladorFenix
DirExistsWarning=no
DisableDirPage=yes
DisableProgramGroupPage=yes

[Components]
Name: "principal"; Description: "Cliente Fenix"; Types: full compact custom; Flags: fixed
Name: "suporte"; Description: "Suporte"; Types: full
Name: "fenixreport"; Description: "Fenix Report"; Types: full
Name: "ajuda"; Description: "Arquivos de Ajuda"; Types: full

[Files]
Source: "H:\fontes\fenixCliente\Cliente\ClienteSAV.exe"; DestDir: "{app}"; CopyMode: alwaysoverwrite; Components: principal
Source: "H:\fontes\fenixCliente\Cliente\fenix.ico"; DestDir: "{app}"; CopyMode: alwaysoverwrite; Components: principal
Source: "H:\fontes\fenixCliente\Cliente\fenixReport.jar"; DestDir: "{app}"; CopyMode: alwaysoverwrite; Components: fenixreport
Source: "H:\fontes\fenixCliente\Cliente\lib\*"; DestDir: "{app}\lib\"; CopyMode: alwaysoverwrite; Components: fenixreport
Source: "H:\fontes\fenixCliente\Cliente\suporte.exe"; DestDir: "{app}"; CopyMode: alwaysoverwrite; Components: suporte
Source: "H:\fontes\fenixCliente\Cliente\suportecliente.exe"; DestDir: "{app}"; CopyMode: alwaysoverwrite; Components: suporte
Source: "H:\fontes\fenixCliente\Cliente\ultravnc\*"; DestDir: "{app}\ultravnc\"; CopyMode: alwaysoverwrite; Components: suporte
Source: "H:\fontes\fenixCliente\Cliente\fenix.ico"; DestDir: "{app}"; CopyMode: alwaysoverwrite; Components: suporte

[Icons]
Name: "{group}\Fenix"; Filename: "{app}\ClienteSAV.exe"; Parameters: " -load sav"; IconFilename: "{app}\fenix.ico"; Components: principal
Name: "{group}\Configuração"; Filename: "{app}\ClienteSAV.exe"; IconFilename: "{app}\fenix.ico"; Components: principal
Name: "{commondesktop}\Fenix"; Filename: "{app}\ClienteSAV.exe"; Parameters: " -load sav"; IconFilename: "{app}\fenix.ico"; Components: principal
Name: "{commonappdata}\Microsoft\Internet Explorer\Quick Launch\Fenix"; Filename: "{app}\ClienteSAV.exe"; Parameters: " -load sav"; IconFilename: "{app}\fenix.ico"; Components: principal
Name: "{group}\Suporte\Conectar ao Suporte"; Filename: "{app}\suportecliente.exe"; WorkingDir: "{app}"; IconFilename: "{app}\fenix.ico"; Components: suporte
Name: "{group}\Suporte\Prestar Suporte"; Filename: "{app}\suporte.exe"; WorkingDir: "{app}"; IconFilename: "{app}\fenix.ico"; Components: suporte
Name: "{group}\Suporte\Registro de Solicitação"; Filename: "http://suporte.basepro.com.br/"



