; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Atualização Fenix Cliente
AppVerName=Atualização Fenix Cliente 2021a
AppPublisher=BasePro
AppPublisherURL=http://www.basepro.com.br
AppSupportURL=http://www.basepro.com.br
AppUpdatesURL=http://www.basepro.com.br
DefaultDirName=c:\Fenix
DefaultGroupName=Fenix
OutputDir=C:\Cliente
OutputBaseFilename=FenixCliente2021a
DirExistsWarning=no
DisableDirPage=yes
DisableProgramGroupPage=yes

[Files]
Source: "C:\Cliente\Update2021a\Atualiza2021a.reg"; DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: "C:\Cliente\ClienteSAV.exe"; DestDir: "{app}"; CopyMode: alwaysoverwrite
Source: "C:\Cliente\fenix.ico"; DestDir: "{app}"; CopyMode: alwaysoverwrite


[Icons]
Name: "{group}\Fenix"; Filename: "{app}\ClienteSAV.exe"; Parameters: " -load sav"; IconFilename: "{app}\fenix.ico"
Name: "{group}\Configuração"; Filename: "{app}\ClienteSAV.exe"; IconFilename: "{app}\fenix.ico"
Name: "{group}\Acesso\Remoto"; Filename: "{app}\remoto.reg"; IconFilename: "{app}\fenix.ico"
Name: "{commonappdata}\Microsoft\Internet Explorer\Quick Launch\Fenix"; Filename: "{app}\ClienteSAV.exe"; Parameters: " -load sav"; IconFilename: "{app}\fenix.ico"
Name: "{commondesktop}\Fenix"; Filename: "{app}\ClienteSAV.exe"; Parameters: " -load sav"; IconFilename: "{app}\fenix.ico"



[Run]
Filename: "regedit "; Parameters: "{app}\Atualiza2021a.reg"

